### PR TITLE
Update `send` proc, enable send masked frames by default

### PR DESCRIPTION
**Pull request by ba0f3**
Update `send` proc, enable send masked frames by default, able to disable via `masked` flags

### CODE REVIEW

**Comment by treeform** [comment]
I am not a huge fan of masking, its easy to reverse - giving you fake security. Just using wss:// is way better alternative. It slows down your code and ads an extra 4 bytes to every packet. 

But after reading the spec on masking it appears to be a requirement:
```a client MUST mask all frames that it
   sends to the server (see Section 5.3 for further details).  (Note
   that masking is done whether or not the WebSocket Protocol is running
   over TLS.)  The server MUST close the connection upon receiving a
   frame that is not masked.  In this case, a server MAY send a Close
   frame with a status code of 1002 (protocol error) as defined in
   Section 7.4.1.  A server MUST NOT mask any frames that it sends to
   the client.  A client MUST close a connection if it detects a masked
   frame. ```
https://tools.ietf.org/html/rfc6455#section-5.1

I think you can't just add mask to a frame. It needs to be a property on the WebSocket object:
* Client WebSocket always masks and errors out if it gets a masked frame from the Server.
* Server WebSocket always does **not** masks and errors out if it gets an unsmaked masked frame from the Client.

I think every one is ignoring these rules... because unmasked frames work just fine everywhere i try... do we need to follow these rules if everyone else is not following them?

Thoughts?

**Comment by treeform** [comment]
Some more on this: https://stackoverflow.com/questions/14174184/what-is-the-mask-in-a-websocket-frame

**Comment by treeform** [comment]
More on the issue: https://github.com/websockets/ws/issues/1194

**Comment by treeform** [comment]
Here is what I am thinking. https://github.com/treeform/ws/pull/15/files 

Not sure maybe it should be behind a flag?

**Comment by ba0f3** [comment]
Thats good enough, thanks

**Pull request closed without merging**
